motor_controller: freenove
motor_cfg: fast

servo_controller: freenove
servo_cfg: default_servo

infrared_controller: freenove
infrared__cfg: default_config

ultrasonic_controller: freenove
ultrasonic_cfg: default_config

camera_controller: pi
camera_cfg: default_config
camera_policy: default_policy

networking: default_config

teleop_cfg: default_config